version: "3.8"
services:
  app:
    build:
      context: .
      target: base
    ports:
      - "80:80"
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
