apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: false
    isDefault: true
    jsonData:
      derivedFields:
        - matcherRegex: "trace_id":\s*"(\w+)"
          name: TraceID
